#!/bin/bash

IMAGE_NAME=jekyllblog

deploy() {
	echo "Deploying..."
}

build() {
	echo "Building..."
}

run() {
	is_image=$(docker ps --all | grep $IMAGE_NAME )
	if [ "$is_image" != "" ]; then
		docker start -ai $IMAGE_NAME
	else
		docker run -ti -v $PWD:/srv/jekyll -p "4000":"4000" --name $IMAGE_NAME jekyll/jekyll:stable jekyll serve --drafts
	fi
}

clear() {
	echo "Clearing..."
}

refresh(){
	clear
	build
	run
}

# Invoke the provided argument
$@
